
services:
 
  postgres:
    image: postgres:15-alpine
    container_name: gamecatalog_postgres
    env_file:
      - ./.env.dev
    restart: always
    environment:
      - POSTGRES_DB=gamecatalog-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - default

volumes:
  pgdata:
    driver: local
    
networks:
  grafana-network:
    external: true