name: "Deploy to Docker Hub and VPS"

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gamecatalog:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Instalar Infisical CLI
      - name: Install Infisical CLI
        run: |
          curl -1sLf 'https://artifacts-cli.infisical.com/setup.deb.sh' | sudo -E bash
          sudo apt-get update && sudo apt-get install -y infisical

      # 2. Buscar Segredos do Infisical e gerar .env
      - name: Fetch Secrets from Infisical
        shell: bash
        env:
          INFISICAL_CLIENT_ID: ${{ secrets.INFISICAL_CLIENT_ID }}
          INFISICAL_CLIENT_SECRET: ${{ secrets.INFISICAL_CLIENT_SECRET }}
        run: |
          infisical login --client-id=$INFISICAL_CLIENT_ID --client-secret=$INFISICAL_CLIENT_SECRET
          # Exporta apenas o necessário para o arquivo que será enviado à VPS
          infisical export --env=prod --format=dotenv > .env.prod
      # 3. Enviar arquivos de infra + .env.prod para a VPS
      - name: Copy Infrastructure Files
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          # Incluímos o .env.prod gerado dinamicamente no passo anterior
          source: "docker-compose.yml,docker-entrypoint.sh,grafana-compose.yml,local-config.yml,.env.prod"
          target: "~/gamecatalog"
          rm: false

      # 4. Comandos Remotos via SSH
      - name: Run remote SSH commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ~/gamecatalog && cd ~/gamecatalog
            
            # Ajuste de permissões
            chmod +x docker-entrypoint.sh
            # Renomeia o arquivo de ambiente para o padrão do Docker Compose
            mv .env.prod .env
            
            # Setup de Redes
            docker network create grafana_network 2>/dev/null || true
            docker network create npm_network 2>/dev/null || true
            
            # Atualização e Deploy
            docker compose pull
            docker compose up -d --remove-orphans
            docker compose -f grafana-compose.yml up -d
            
            # Limpeza
            docker image prune -f