name: "Deploy to VPS"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files via SCP
        uses: appleboy/scp-action@v1
        with:
          port: 22
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: ".,!.git,!.env*" # Bloqueia qualquer .env de ser enviado
          target: "gamecatalog"

      - name: Run remote SSH commands
        uses: appleboy/ssh-action@v1
        with:
          port: 22
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          # Passamos os dados via argumento JSON para evitar que o plugin tente parsear como ENV
          script: |
            cd ~/gamecatalog
            
            # Limpeza radical do .env quebrado que está impedindo o deploy
            find . -name ".env" -delete
            
            # Reconstrói o .env dinamicamente sem usar o parser do plugin
            # Usamos o contexto de secrets do GitHub diretamente no comando 'cat'
            cat << 'EOF' > .env
            ${{ toJSON(secrets) }}
            EOF
            docker network create grafana_network || true
            docker network create npm_network || true
            # Converte o JSON em formato .env e remove as chaves de infraestrutura
            sed -i 's/[{}"]//g; s/: /=/g; s/,$//g; /^$/d' .env
            sed -i '/^SSH_KEY=/d; /^HOST=/d; /^USERNAME=/d; /^GITHUB_TOKEN=/d' .env

            if [ -f grafana-compose.yml ]; then
              docker compose -f grafana-compose.yml up -d
            fi
            
            # Agora o Docker sobe com o .env limpo
            docker compose down
            docker compose up -d --build