name: "Deploy to VPS"

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    env:
      #postgres
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      PGPORT: ${{ secrets.PGPORT }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

      #ssh
      HOST: ${{ secrets.HOST }}
      USERNAME: ${{ secrets.USERNAME }}
      KEY: ${{ secrets.KEY }}

      #grafana
      GF_SECURITY_ADMIN_USER: ${{ secrets.GF_SECURITY_ADMIN_USER }}
      GF_SECURITY_ADMIN_PASSWORD: ${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}

      #abacatepay
      ABACATE_PAY_API: ${{ secrets.ABACATE_PAY_API }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Test SSH access
        uses: appleboy/ssh-action@v1
        with:
          port: 22
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          script: |
            whoami
            pwd
            mkdir ~/test-frontend-temp
            echo "Test folder created. Now removing it..."
            rm -rf ~/test-frontend-temp
            echo "Test folder removed."

      - name: Copy files via SCP
        uses: appleboy/scp-action@v1
        with:
          port: 22
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          source: "."
          target: "node-vps"

      - name: Run remote SSH commands
        uses: appleboy/ssh-action@v1
        with:
          port: 22
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          script: |
            # 1. Configuração do NVM (se você usa nvm na VPS)
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"

            # 2. Exportação das variáveis de ambiente para o Docker Compose
            export POSTGRES_DB="${{ env.POSTGRES_DB }}"
            export POSTGRES_USER="${{ env.POSTGRES_USER }}"
            export POSTGRES_PASSWORD="${{ env.POSTGRES_PASSWORD }}"
            export PGPORT="${{ env.PGPORT }}"
            export DATABASE_URL="${{ env.DATABASE_URL }}"
            # Variáveis adicionais do seu .env
            export HOST="${{ env.HOST }}"
            export KEY="${{ env.KEY }}"
            export USERNAME="${{ env.USERNAME }}"

            export GF_SECURITY_ADMIN_USER="${{ env.GF_SECURITY_ADMIN_USER }}"
            export GF_SECURITY_ADMIN_PASSWORD="${{ env.GF_SECURITY_ADMIN_PASSWORD }}"
            
            export ABACATE_PAY_API="${{ env.ABACATE_PAY_API }}"
            
            # 3. Comandos de Deploy
            cd /root/node-vps/

            echo "Stopping and removing old containers..."
            docker compose down
            
            echo "Run build"
            pnpm run build
            pnpm run migrate
            echo "Removing old images..."
            docker image prune -af
            
            echo "Building and starting new containers..."
            # O Docker Compose usará as variáveis exportadas

            docker network create grafana-network || true
            docker compose -f grafana-compose.yml up -d
            docker compose up -d --build
            
            echo "Cleaning unused resources..."
            docker system prune -af

            echo "✅ Server rebuilt and started successfully!"